#!/usr/bin/env perl
# check-http-rewriting URL1 URL2 ensures that URL1 rewrites to URL2

use strict;
use English;
$WARNING = 1;

if (scalar(@ARGV) != 2) {
  die "call $0 with two arguments";
}

my ($url, $goal) = @ARGV;

if ($url !~ m{^https?://}) {
  $url = "http://$url";
}
if ($goal !~ m{^https?://}) {
  $goal = "http://$goal";
}

if ($url eq $goal) {
  exit 0;
}

my $wget_output = `wget --spider $url 2>&1`;

if ($wget_output !~ /.*\nLocation: \Q$goal\E \[following\]\n/m) {
  print STDERR "Failed command: $0 $url $goal\nFailed rewriting:\n  $url\ndoes not rewrite to\n  $goal\n$wget_output";
  exit 1;
}

exit 0;
