#!/bin/sh -f

# Execute a command on every machine in file cse-machines.

SCRIPTPATH=$(dirname "$(readlink -f "$0")")

grep -v '^ *#' <"$SCRIPTPATH/cse-machines" | while IFS= read -r host; do
  echo "${host}:"
  # shellcheck disable=SC2029
  ssh -X "$host" "$@" </dev/null
done
