#! /bin/bash
# Expand a .jar file into a directory.
# If the .jar file is "foo.jar", the directory is "foo-jar".

for jarfile in "$@"; do
  case "${jarfile}" in
    *.jar) ;;
    *)
      echo "expand-jar: not a .jar file: ${jarfile}" >&2
      exit 1
      ;;
  esac
  dir="${jarfile%.jar}-jar"
  rm -rf "${dir}"
  mkdir "${dir}"
  cp -p "${jarfile}" "${dir}"
  (cd "${dir}" && jar xf "$(basename "${jarfile}")")
done
