#!/bin/bash
# Uses bash-only syntax: (( )), [[ ]], and ${line:offset:len}.

# From http://askubuntu.com/questions/259739/kswapd0-is-taking-a-lot-of-cpu

## run as cron, thus no $PATH, thus need to define all absolute paths
top=/usr/bin/top
grep=/bin/grep

top=$($top -bn1 -o '%CPU' -u0 | $grep -m2 -E "%CPU|kswapd0")

IFS='
'
set -f

i=0

for line in $top; do
  #echo $i $line

  if ! ((i++)); then
    pos=${line%%%CPU*}
    pos=${#pos}
    #echo $pos
  else
    # top right-aligns the value under the heading, so the value
    # ends where the heading ends, whatever the column's width.
    cpu=${line:0:(($pos + 4))}
    cpu=${cpu##* }
    # (( )) handles only integers, but %CPU is a decimal fraction.
    cpu=${cpu%%[.,]*}
    #echo $cpu
  fi

done

[[ $cpu =~ ^[0-9]+$ ]] \
  && ((cpu >= 90)) \
  && echo 1 > /proc/sys/vm/drop_caches \
  && echo "$$ $0: cache dropped (kswapd0 %CPU=$cpu)" >&2 \
  && exit 1

exit 0
