#! /bin/sh

export COMMAND="$HOME/bin/Linux-x86_64/checkdates"

export SUBJECT="Checkdates"

# On Solaris, don't use "mail", which is /bin/mail;
# use /usr/ucb/mail, which understands the -s argument.
# On Debian, must use /usr/bin/mail instead of /bin/mail.
# setenv MAILCOMMAND /usr/bin/mail
export MAILE="$HOME/bin/src/plume-scripts/mail-e"

${COMMAND} 2>&1 "${MAILE}" -s "${SUBJECT}" mernst@alum.mit.edu scath@alumni.duke.edu
