#! /usr/bin/env python3

"""Review weekly mail in Gmail.

Usage: mail-review-weekly
"""

import time
import webbrowser

# This stopped working in April 2026.
# usernames = ["mernst@cs.washington.edu", "michael.ernst"]
usernames = ["0", "1"]


def mail_search(search_term: str) -> None:
    """Search for a term in both of my inboxes."""
    for username in usernames:
        webbrowser.open("https://mail.google.com/mail/u/" + username + "/#search/" + search_term)
        time.sleep(0.3)


def mail_label(search_term: str) -> None:
    """Search for a label in both of my inboxes."""
    for username in usernames:
        webbrowser.open("https://mail.google.com/mail/u/" + username + "/#label/" + search_term)
        time.sleep(0.3)


print("Part 1")

# Merged pull requests

mail_label("pr-merged")

# Kids' daily & weekly email

mail_search("category%3Apromotions+label%3Asilas+label%3Ainbox")
mail_search("category%3Asocial+label%3Asilas+label%3Ainbox")
# mail_search("category%3Apromotions+label%3Amaeve+label%3Ainbox")
# mail_search("category%3Asocial+label%3Amaeve+label%3Ainbox")

# Specific promotions email

mail_search("from%3Ascancafe+label%3Ainbox")
mail_search("from%3Aextracare+label%3Ainbox")

input("Press ENTER")
print("Part 2")

## TODO: Change these to mail_search
# The regular mail_label() does not work with additional keywords.
# These come early so that the delay-weekly label might update before I get to it.
for username in usernames:
    webbrowser.open(
        "https://mail.google.com/mail/u/" + username + "/#search/label%3Adelay-weekly+seworld"
    )
for username in usernames:
    webbrowser.open(
        "https://mail.google.com/mail/u/" + username + "/#search/label%3Adelay-weekly+ecoop-info"
    )
mail_search("label%3Adelay-junk+%22micheal%22")
mail_search("to:it-fmeurope-events")

input("Press ENTER")
print("Part 3")

# Weekly (and daily) email

mail_label("delay-bulk")
mail_label("delay-daily")
mail_label("delay-junk")
mail_label("delay-weekly")

input("Press ENTER")
print("Part 4")

# Social & promotions email

mail_search("category%3Apromotions+label%3Ainbox")
mail_search("category%3Asocial+label%3Ainbox")
mail_search("category%3Aupdates+label%3Ainbox+label%3Acommerce")
mail_search("category%3Aupdates+label%3Ainbox")
mail_search("to%3Aprogress-reports%40cs.washington.edu+label%3Ainbox")
mail_search("category%3Aforums+label%3Ainbox")
