#!/bin/sh

## Every command in this file is temporary.  It keeps dependent branches up to date.

set -e
set -u

while [ $# -gt 0 ]; do
  case $1 in
    --debug)
      # shellcheck disable=SC2034 # DEBUG is not used yet
      DEBUG=--debug
      VERBOSE=true
      shift # past argument
      ;;
    --verbose)
      # shellcheck disable=SC2034 # VERBOSE is not used yet
      VERBOSE=true
      shift # past argument
      ;;
    -*)
      echo "Unknown option $1"
      exit 2
      ;;
    *)
      echo "Do not pass arguments to $0"
      exit 2
      ;;
  esac
done

### Environment variables

## These constructions suppress warnings from shellcheck.
if [ -z "${cf+x}" ]; then
  echo 'Not set: cf'
fi
if [ -z "${h+x}" ]; then
  echo 'Not set: h'
fi
if [ -z "${inv+x}" ]; then
  echo 'Not set: inv'
fi
if [ -z "${t+x}" ]; then
  echo 'Not set: t'
fi

orig_cf="$(basename "$(readlink -f "$cf")")"

### Beepbeep

cd ~/java

cronic git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-buildfile-for-daikon

cronic git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-daikon

cronic git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-github-actions-update

cronic git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-nullness

cronic git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-resourceleak

### Checker Framework

cd "$t"

cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-canonical-annotation

cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-dont-insert-irrelevant

## Confidential Checker

cd "$t"/libraries

cronic git-push-to --nocompile \
  jdk-branch-master \
  jdk-fork-iywang2016-branch-iywang

cd "$t"

cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-iywang2016-branch-iywang

## Side effects

cd "$t"

cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-purity-checker-misc \
  checker-framework-fork-mernst-branch-side-effects-only-2-pre

cronic git-push-to \
  checker-framework-fork-mernst-branch-side-effects-only-2-pre \
  checker-framework-fork-mernst-branch-side-effects-only-2

cd "$t"/libraries

cronic git-push-to --nocompile \
  jdk-branch-master \
  jdk-fork-mernst-branch-side-effects-only-2

## Gradle

cd "$t"

cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-gradle-root-project-libs \
  checker-framework-fork-mernst-branch-gradle-deprecation-pre

cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-gradle-root-project-create-check-type-task \
  checker-framework-fork-mernst-branch-gradle-deprecation-pre

## Resource Leak Checker for collections

usecf checker-framework-fork-iamsanjaymalakar-branch-rlc-for-collections

cd "$t"/libraries

cronic git-push-to --nocompile \
  jdk-branch-master \
  jdk-fork-iamsanjaymalakar-branch-rlc-for-collections

cd "$t"

cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-iamsanjaymalakar-branch-rlc-for-collections

usecf "$orig_cf"

## Modifiability

usecf checker-framework-fork-yukiyang31-branch-modifiability

cd "$t"/libraries

cronic git-push-to --nocompile \
  jdk-branch-master \
  jdk-fork-yukiyang31-branch-modifiability \
  jdk-fork-smillst-branch-modifiability

cd "$t"
cronic git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-yukiyang31-branch-modifiability \
  checker-framework-fork-smillst-branch-modifiability

usecf "$orig_cf"

### Daikon

cd "$inv"

cronic git-push-to \
  daikon-branch-master \
  daikon-fork-markro49-branch-java-24-dcomp-3

### Harvest

cd "$h"

cronic git-push-to --nocompile \
  rust_verification \
  rust_verification-branch-review-pre

cronic git-push-to --nocompile \
  rust_verification-branch-review-pre \
  rust_verification-branch-review

## Restore environment

usecf "$orig_cf"
