#!/bin/sh

## Every command in this file is temporary.  It keeps dependent branches up to date.

set -e

while [ $# -gt 0 ]; do
  case $1 in
    --debug)
      # shellcheck disable=SC2034 # DEBUG is not used yet
      DEBUG=--debug
      VERBOSE=true
      shift # past argument
      ;;
    --verbose)
      # shellcheck disable=SC2034 # VERBOSE is not used yet
      VERBOSE=true
      shift # past argument
      ;;
    -*)
      echo "Unknown option $1"
      exit 2
      ;;
    *)
      echo "Do not pass arguments to $0"
      exit 2
      ;;
  esac
done

## Environment variables

## These constructions suppress warnings from shellcheck.
if [ -z "${cf+x}" ]; then
  echo 'Not set: inv'
fi
if [ -z "${inv+x}" ]; then
  echo 'Not set: inv'
fi
if [ -z "${t+x}" ]; then
  echo 'Not set: t'
fi

orig_cf="$(basename "$(readlink -f "$cf")")"

### Beepbeep

cd ~/java

git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-buildfile-for-daikon

git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-daikon

git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-github-actions-update

git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-nullness

git-push-to \
  beepbeep-3-branch-master \
  beepbeep-3-fork-mernst-branch-resourceleak

### Checker Framework

cd "$t"

git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-canonical-annotation

git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-dont-insert-irrelevant

#### Confidential Checker

git-push-to --nocompile \
  jdk-branch-master \
  jdk-fork-iywang2016-branch-iywang \
  jdk-fork-mernst-branch-iywang2016-iywang

git-push-to --nocompile \
  jdk-fork-mernst-branch-iywang2016-iywang \
  jdk-fork-mernst-branch-iywang2016-iywang-without-stubs

git-push-to --nocompile \
  jdk-fork-mernst-branch-iywang2016-iywang \
  jdk-fork-mernst-branch-iywang2016-iywang-without-tests

#### Side effects

git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-purity-checker-misc \
  checker-framework-fork-mernst-branch-side-effects-only-2-pre

git-push-to \
  checker-framework-fork-mernst-branch-side-effects-only-2-pre \
  checker-framework-fork-mernst-branch-side-effects-only-2

git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-mernst-branch-security-advisory-GHSA-g4jf-chwx-8gv4

#### Gradle

cd "$t" \
  && git-push-to \
    checker-framework-branch-master \
    checker-framework-fork-mernst-branch-gradle-root-project-libs \
    checker-framework-fork-mernst-branch-gradle-deprecation-pre \
  && git-push-to \
    checker-framework-branch-master \
    checker-framework-fork-mernst-branch-gradle-root-project-ext \
    checker-framework-fork-mernst-branch-gradle-deprecation-pre \
  && git-push-to \
    checker-framework-branch-master \
    checker-framework-fork-mernst-branch-gradle-providers-get-property \
    checker-framework-fork-mernst-branch-gradle-deprecation-pre \
  && git-push-to \
    checker-framework-branch-master \
    checker-framework-fork-mernst-branch-gradle-root-project-create-check-type-task \
    checker-framework-fork-mernst-branch-gradle-deprecation-pre \
  && true

cd "$t" \
  && git-push-to \
    checker-framework-branch-master \
    checker-framework-fork-mernst-branch-local-vars-2 \
    checker-framework-fork-mernst-branch-equals-shallow-effective \
    checker-framework-fork-mernst-branch-check-receiver-override \
  && cd "$t" \
  && git-push-to \
    checker-framework-branch-master \
    checker-framework-fork-mernst-branch-local-vars-2 \
    checker-framework-fork-mernst-branch-warn-unneeded-in-tests \
  && cd "$t" \
  && git-push-to \
    checker-framework-branch-master \
    checker-framework-fork-mernst-branch-warn-unneeded-efficiency \
    checker-framework-fork-mernst-branch-warn-unneeded-in-tests \
  && true

#### Resource Leak Checker for collections

usecf checker-framework-fork-iamsanjaymalakar-branch-rlc-for-collections

git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-iamsanjaymalakar-branch-rlc-for-collections \
  && usecf "$orig_cf"

#### Modifiability

usecf checker-framework-fork-yukiyang31-branch-modifiability

(
  cd "$t"/libraries \
    && git-push-to --nocompile \
      jdk-branch-master \
      jdk-fork-yukiyang31-branch-modifiability \
      jdk-fork-smillst-branch-modifiability
)

cd "$t"
git-push-to \
  checker-framework-branch-master \
  checker-framework-fork-yukiyang31-branch-modifiability \
  checker-framework-fork-smillst-branch-modifiability

usecf "$orig_cf"

### Daikon

cd "$inv"
git-push-to \
  daikon-branch-master \
  daikon-fork-markro49-branch-java-24-dcomp-3

## Restore environment

usecf "$orig_cf"
