#!/bin/sh

while [ $# -gt 0 ]; do
  case $1 in
    --debug)
      DEBUG=--debug
      shift # past argument
      ;;
    -*)
      echo "Unknown option $1"
      exit 2
      ;;
    *)
      echo "Do not pass arguments to $0"
      exit 2
      ;;
  esac
done

# Start removing orphaned branch directories as early as possible,
# because it takes a while to complete and we don't want error
# messages later about clones that belong to branches that have been
# deleted.
# shellcheck disable=SC2046 # git-orphaned-branches prints multiple directories
(cd && rm -rf $(git-orphaned-branches)) &
# shellcheck disable=SC2046 # git-orphaned-branches prints multiple directories
if [ -d /scratch/mernst/clones ]; then
  (cd /scratch/mernst/clones && rm -rf $(git-orphaned-branches)) &
fi

# shellcheck disable=SC2086
mdevccommit ${DEBUG}
# shellcheck disable=SC2086
mdevcupdate ${DEBUG}
# shellcheck disable=SC2086
cronic mdevcpushto ${DEBUG}

java -ea -cp "${HOME}/java/plume-lib/multi-version-control/build/libs/multi-version-control-all.jar" org.plumelib.multiversioncontrol.MultiVersionControl update

## Replace `.plume-scripts` directories by symbolic links.

# By design, this only finds directories, not symbolic links, named `.plume-scripts`.
find "$HOME" -type d -name .plume-scripts -exec sh -c '
  cd $(dirname "$dir")
  rm -rf .plume-scripts
  ln -sr "$HOME"/bin/src/plume-scripts .plume-scripts
  ' sh {} \; &

if [ -d /scratch/mernst/clones ]; then
  find /scratch/mernst/clones -type d -name .plume-scripts -exec sh -c '
    cd $(dirname "$dir")
    rm -rf .plume-scripts
    ln -sr /scratch/mernst/clones/plume-lib/plume-scripts .plume-scripts
    ' sh {} \; &
fi

## Run `git prune` where needed.

for dir in $(locate .git/gc.log | sed 's:/.git/gc.log$::'); do
  git -C "$dir" prune
  rm -f "$dir"/.git/gc.log
done

## Notify about files that require attention

find "${HOME}" -name SKIP-REQUIRE-JAVADOC
if [ -d /scratch/mernst/clones ]; then
  find /scratch/mernst/clones -name checker-framework-fork-opprop -prune -o \( -name SKIP-REQUIRE-JAVADOC -print0 \)
fi

# Warn about conflict markers in directories that are synchronized.
for dir in ~/sync ~/private ~/public_html/tmp72112; do
  find "${dir}" -name '*.sync-conflict-*'
done
