#!/bin/sh

while [ $# -gt 0 ]; do
  case $1 in
    --debug)
      DEBUG=--debug
      shift # past argument
      ;;
    -*)
      echo "Unknown option $1"
      exit 2
      ;;
    *)
      echo "Do not pass arguments to $0"
      exit 2
      ;;
  esac
done

# Start removing orphaned branch directories as early as possible,
# because it takes a while to complete and we don't want error
# messages later about clones that belong to branches that have been
# deleted.
# shellcheck disable=SC2046 # git-orphaned-branches prints multiple directories
(cd && rm -rf $(git-orphaned-branches)) &
# shellcheck disable=SC2046 # git-orphaned-branches prints multiple directories
if [ -d /scratch/mernst/clones ]; then
  (cd /scratch/mernst/clones && rm -rf $(git-orphaned-branches)) &
fi

# shellcheck disable=SC2086
mdevccommit ${DEBUG}
# shellcheck disable=SC2086
mdevcupdate ${DEBUG}
# shellcheck disable=SC2086
cronic mdevcpushto ${DEBUG}

java -ea -cp "${HOME}/java/plume-lib/multi-version-control/build/libs/multi-version-control-all.jar" org.plumelib.multiversioncontrol.MultiVersionControl update

## Replace `.plume-scripts` directories by symbolic links.

# By design, this only finds directories named `.plume-scripts`.
# `find -exec` works but issues a warning (because we are changing directories out from under it.)
# Argumets are: directory in which to search, dir to replace, file to link to.
replace_dir_by_link() {
  dir="$1"
  to_replace="$2"
  replacement="$3"
  tempfile=$(mktemp)
  find "$dir" -type d -name "${to_replace}" > "${tempfile}"
  while IFS= read -r line; do
    cd "$(dirname "$line")" || exit
    rm -rf "${to_replace}"
    ln -sr "$replacement" "$to_replace"
  done < "${tempfile}"
  rm -f "${tempfile}"
}

replace_dir_by_link "$HOME" .git-scripts "$HOME/bin/src/git-scripts" &
replace_dir_by_link "$HOME" .html-tools "$HOME/bin/src/html-tools" &
replace_dir_by_link "$HOME" .plume-scripts "$HOME/bin/src/plume-scripts" &
if [ -d /scratch/mernst/clones ]; then
  replace_dir_by_link /scratch/mernst/clones .git-scripts /scratch/mernst/clones/bin/src/git-scripts &
  replace_dir_by_link /scratch/mernst/clones .html-tools /scratch/mernst/clones/bin/src/html-tools &
  replace_dir_by_link /scratch/mernst/clones .plume-scripts /scratch/mernst/clones/bin/src/plume-scripts &
fi

## Run `git prune` where needed.

for dir in $(locate .git/gc.log | sed 's:/.git/gc.log$::'); do
  git -C "$dir" prune
  rm -f "$dir"/.git/gc.log
done

## Notify about files that require attention

find "${HOME}" -name SKIP-REQUIRE-JAVADOC
if [ -d /scratch/mernst/clones ]; then
  find /scratch/mernst/clones -name checker-framework-fork-opprop -prune -o \( -name SKIP-REQUIRE-JAVADOC -print0 \)
fi

# Warn about conflict markers in directories that are synchronized.
for dir in ~/sync ~/private ~/public_html/tmp72112; do
  find "${dir}" -name '*.sync-conflict-*'
done
