#!/bin/bash -l
# Note the "-l" on the line above:  I want my startup to run.  A login shell
# reads ~/.bash_profile, which reads ~/.profile (which sets PATH) and ~/.bashrc
# (which reads ~/.aliases, where the `xe` function used below is defined).

export PAGHOST="${PAGHOST:-manioc.csail.mit.edu}"

# "$site" is set by my startup files, if at all.
if [ "${site:-}" != "csail" ]; then
  if ping -q -c 1 -w 1 "${PAGHOST}" > /dev/null; then
    remote=1
  fi
fi

# "$remote" is set if we are remote, *and* we have connectivity to manioc.
# if [ -n "${remote:-}" ]; then
#   echo "remote"
# else
#   echo "non-remote"
# fi

if [ -n "${remote:-}" ]; then
  xe "${PAGHOST}"
else
  emacs &
fi

# This code is not right.
if [ -n "${remote:-}" ]; then
  # I'm willing to run ical locally on my laptop, but if manioc is available,
  # then use it instead.
  ssh -f "${PAGHOST}" ical -iconic
else
  if pgrep -f ical > /dev/null; then
    ical_running=yes
  else
    ical_running=no
  fi
  case "$DISPLAY" in
    manioc:0.0 | :0 | :0.0) on_manioc_display=yes ;;
    *) on_manioc_display=no ;;
  esac
  # Run ical if it is not running, or if I'm not logged into manioc
  if [ "$ical_running" = no ] || [ "$on_manioc_display" = no ]; then
    ical -iconic &
  fi
fi

# if ! pgrep -f guidescope > /dev/null; then
#   cd "$HOME/bin/src/guidescope" && etc/guidescope/guide > /dev/null 2>&1 &
# fi

# netscape -iconic &
# mozilla -iconic &
# "-iconic" does not seem to be supported any longer
# mozilla -P mernst &
# firefox -P mernst &
firefox &
