#!/bin/sh -f
# call with: myxloads [--show] w h sx sy maxx maxy
#  All arguments are optional.
#  w and h are width and height of each xload window
#  sx and sy are the starting x and y coordinates
#  maxx and maxy are the maximum x and y coordinates
#  optional first argument "--show" means print commands, don't execute them

show=0
if [ "$1" = "--help" ]; then
  show=1
  shift
fi
if [ "$1" = "--show" ]; then
  show=1
  shift
fi

w=${1:-48}
h=${2:-45}
sx=${3:-0}
sy=${4:-30}
maxx=${5:-100}
# maxy=${6:-300}
initsx=$sx
# initsy=$sy
# thishost=$(hostname -s)

SCRIPTPATH=$(dirname "$(readlink -f "$0")")

grep -v '^ *#' < "$SCRIPTPATH/cse-machines" | while IFS= read -r host; do
  cmd="ssh -X $host nice xload -geometry =${w}x${h}-${sx}-${sy} -jumpscroll 1"
  if [ $show = "1" ]; then
    echo "$cmd &"
  else
    $cmd &
    # Avoid conflicts over locking the authority file
    sleep .5
  fi
  sx=$((sx + w))
  sx=$((sx + 4))
  if [ "$sx" -gt "$maxx" ]; then
    sx=$initsx
    sy=$((sy + h))
    sy=$((sy + 4))
  fi
done
