#!/bin/bash -l
# The "-l" on the line above makes this a login shell, so that my startup files
# are read: ~/.bash_profile reads ~/.profile, which sets PATH.
# Not named "printmail" because that is part of elm.
# Invoke like this:  "print-mail bulk" or "print-mail -o outfile.ps bulk"

usage() {
  echo "Usage: $0 [-o outfile.ps] dropname       eg: $0 bulk" 1>&2
}

outfile=""
dropname=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    -o)
      shift
      if [ "$#" -eq 0 ]; then
        echo "Error: -o requires an argument" 1>&2
        usage
        exit 1
      fi
      outfile="$1"
      ;;
    *)
      if [ -n "$dropname" ]; then
        echo "Error: supplied two drop names" 1>&2
        usage
        exit 1
      fi
      dropname="$1"
      ;;
  esac
  shift
done

if [ -z "$dropname" ]; then
  echo "Error: no drop name supplied" 1>&2
  usage
  exit 1
fi

cd ~/.mail || exit 1

if [ ! -e ".maildrop-$dropname" ]; then
  echo "File .maildrop-$dropname does not exist" 1>&2
  exit 1
fi

if [ ! -s ".maildrop-$dropname" ]; then
  echo "File .maildrop-$dropname is empty" 1>&2
  exit 1
fi

# movemail .maildrop-$dropname $dropname-mail
# /usr/lib/emacs/21.4/i386-linux/movemail .maildrop-$dropname $dropname-mail
# /usr/libexec/emacs/22.2/i686-pc-linux-gnu/movemail .maildrop-$dropname $dropname-mail
movemail ".maildrop-$dropname" "$dropname-mail" || exit 1
# Remove .maildrop file, which isn't used since I no longer use procmail.
rm -f ".maildrop-$dropname" || exit 1
emacs -batch "$dropname-mail" -l ~/.emacs -l ~/emacs/mail-simplify -f clean-mail-buffer -f save-buffer > /dev/null 2>&1
if [ -n "$outfile" ]; then
  enscript --pretty-print -2r -o "$outfile" "$dropname-mail"
  echo "Created $outfile; consider deleting $dropname-mail-$$"
else
  enscript --pretty-print -2r "$dropname-mail"
  echo "Printed $dropname-mail; consider deleting $dropname-mail-$$"
fi
mv "$dropname-mail.~1~" "$dropname-mail-$$.~1~"
mv "$dropname-mail" "$dropname-mail-$$"
chmod og-rw "$dropname-mail-$$"*
