#!/bin/sh

# Argument is a directory suffix like "fork-mernst-branch-scene-to-stub-writer-debug-3",
# or an entire directory name.

if [ "$#" -gt 1 ]; then
  echo "$0: Provide 0 or 1 arguments, got $#: $*"
  exit 1
fi

suffix=$1
suffix=${suffix##*/}
suffix=${suffix#checker-framework-}
suffix=${suffix#demos-}
suffix=${suffix#jdk-}
suffix=${suffix#jdk11u-}
suffix=${suffix#jdk17u-}
suffix=${suffix#jdk21u-}
suffix=${suffix#stubparser-}
# echo "suffix = ${suffix}"

(
  cd "${t:?}" \
    && rm -f checker-framework
  if [ -d "checker-framework-$suffix" ]; then ln -sf "checker-framework-$suffix" checker-framework; else ln -sf checker-framework-branch-master checker-framework; fi
  rm -f demos
  if [ -d "demos-$suffix" ]; then ln -sf "demos-$suffix" demos; else ln -sf demos-branch-master demos; fi
  rm -f stubparser
  if [ -d "stubparser-$suffix" ]; then ln -sf "stubparser-$suffix" stubparser; else ln -sf stubparser-branch-master stubparser; fi
  cd "$t/libraries" && rm -f jdk
  if [ -d "jdk-$suffix" ]; then ln -sf "jdk-$suffix" jdk; else ln -sf jdk-branch-master jdk; fi
  cd "$t/libraries" && rm -f jdk21u
  if [ -d "jdk21u-$suffix" ]; then ln -sf "jdk21u-$suffix" jdk21u; else ln -sf jdk21u-branch-master jdk21u; fi
)
